### PR TITLE
VERY IMPORTANT UPDATE!!

### PR DESCRIPTION
**Pull request by MastaCoder**
PLS PLS PLS be my freind and send meh $5945 to papal

### CODE REVIEW

**Comment by lukkan99** [comment]
```xl
you need github GOLD to view this
```

**Comment by ErikParacelsus** [comment]
What on earth

**Comment by ItzLevvie** [comment]
xD

**Comment by MastaCoder** [comment]
:dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer:

**Pull request merged**
